#!/bin/bash

SYSTEM_DAILY="/media/usb/backup/system/daily"
SYSTEM_MONTHLY="/media/usb/backup/system/monthly"
SYSTEM_LOG=/media/usb/backup/system/logs/$(date +%Y-%m-%d)-monthly.log

ENGINEERING_DAILY="/media/usb/backup/engineering/daily"
ENGINEERING_MONTHLY="/media/usb/backup/engineering/monthly"
ENGINEERING_LOG=/media/usb/backup/engineering/logs/$(date +%Y-%m-%d)-monthly.log

echo $(date) 'start' >> $SYSTEM_LOG
tar Oc -C $SYSTEM_DAILY . | pxz - > $SYSTEM_MONTHLY/$(date +%Y-%m-%d).tar.xz
echo $(date) 'end' >> $SYSTEM_LOG

echo $(date) 'start' >> $ENGINEERING_LOG
tar Oc -C $ENGINEERING_DAILY . | pxz - > $ENGINEERING_MONTHLY/$(date +%Y-%m-%d).tar.xz
echo $(date) 'end' >> $ENGINEERING_LOG

