#!/bin/bash

BACKUP_DAILY="/media/data/backup/system/daily"
BACKUP_MONTHLY="/media/data/backup/system/monthly"
LOG_FILE=/media/data/backup/system/logs/$(date +%Y-%m-%d)-monthly.log

echo $(date) 'start' >> $LOG_FILE

tar Oc -C $BACKUP_DAILY . | pxz - > $BACKUP_MONTHLY/$(date +%Y-%m-%d).tar.xz

echo $(date) 'end' >> $LOG_FILE
