#!/bin/bash

SYSTEM_ROOT="/"
SYSTEM_BOOT="/media/boot/"
ENGINEERING_ROOT="/media/data/engineering/"

SYSTEM_ROOT_DAILY="/media/usb/backup/system/daily"
SYSTEM_BOOT_DAILY=$SYSTEM_ROOT_DAILY/media/boot
ENGINEERING_DAILY="/media/usb/backup/engineering/daily"

SYSTEM_LOG=/media/usb/backup/system/logs/$(date +%Y-%m-%d)-daily.log
ENGINEERING_LOG=/media/usb/backup/engineering/logs/$(date +%Y-%m-%d)-daily.log

DAYS_TO_LOG=("Sat" "Sun" "Mon")

DATE=$(date)

for day in ${DAYS_TO_LOG[@]}; do
    if [[ $DATE == *$day* ]]; then
        echo $(date) 'start' >> $SYSTEM_LOG

        rsync -avAX --delete --exclude={"/var/cache/apt/archives/*","/var/lib/lxcfs/*","/var/log/*","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} $SYSTEM_ROOT $SYSTEM_ROOT_DAILY >> $SYSTEM_LOG

        rsync -avAX --delete $SYSTEM_BOOT $SYSTEM_BOOT_DAILY >> $SYSTEM_LOG

        echo $(date) 'end' >> $SYSTEM_LOG

        echo $(date) 'start' >> $ENGINEERING_LOG
        rsync -avAX --delete $ENGINEERING_ROOT $ENGINEERING_DAILY >> $ENGINEERING_LOG
        echo $(date) 'end' >> $ENGINEERING_LOG

    fi
done

