#!/bin/bash

BACKUP_DAILY="/media/usb/backup/ubuntu/daily"
LOG_FILE=/media/usb/backup/ubuntu/logs/$(date +%Y-%m-%d)-daily.log

DAYS_TO_LOG=("Sat" "Sun" "Mon")

DATE=$(date)

for day in ${DAYS_TO_LOG[@]}; do
    if [[ $DATE == *$day* ]]; then
        echo $(date) 'start' >> $LOG_FILE
        rsync -avAX --delete --exclude={"/var/cache/apt/archives/*","/var/lib/lxcfs/*","/var/log/*","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} / $BACKUP_DAILY >> $LOG_FILE

        echo $(date) 'end' >> $LOG_FILE
    fi
done
