#!/bin/bash

BACKUP_DAILY="/media/data/backup/system/daily"
LOG_FILE=/media/data/backup/system/logs/$(date +%Y-%m-%d)-daily.log

DAYS_TO_LOG=("Sat" "Sun" "Mon")

DATE=$(date)

for day in ${DAYS_TO_LOG[@]}; do
    if [[ $DATE == *$day* ]]; then
        echo $(date) 'start' >> $LOG_FILE

        rsync -avAX --delete --exclude={"/var/cache/apt/archives/*","/var/lib/lxcfs/*","/var/log/*","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} / $BACKUP_DAILY >> $LOG_FILE

        rsync -avAX --delete /media/boot $BACKUP_DAILY/media/boot >> $LOG_FILE

        rsync -avAX --delete /media/data/engineering $BACKUP_DAILY/media/data/engineering >> $LOG_FILE

        echo $(date) 'end' >> $LOG_FILE
    fi
done
