#!/bin/bash

BACKUP_DAILY="/media/data/backup/system/daily/"
BACKUP_WEEKLY="/media/data/backup/system/weekly"
LOG_FILE=/media/data/backup/system/logs/$(date +%Y-%m-%d)-weekly.log

echo $(date) 'start' >> $LOG_FILE

rsync -aAXv --delete $BACKUP_DAILY $BACKUP_WEEKLY >> $LOG_FILE

echo $(date) 'end' >> $LOG_FILE
