#!/bin/bash

SYSTEM_DAILY="/media/usb/backup/system/daily/"
SYSTEM_WEEKLY="/media/usb/backup/system/weekly"
SYSTEM_LOG=/media/usb/backup/system/logs/$(date +%Y-%m-%d)-weekly.log

ENGINEERING_DAILY="/media/usb/backup/engineering/daily/"
ENGINEERING_WEEKLY="/media/usb/backup/engineering/weekly"
ENGINEERING_LOG=/media/usb/backup/engineering/logs/$(date +%Y-%m-%d)-weekly.log

echo $(date) 'start' >> $SYSTEM_LOG
rsync -aAXv --delete $SYSTEM_DAILY $SYSTEM_WEEKLY >> $SYSTEM_LOG
echo $(date) 'end' >> $SYSTEM_LOG

echo $(date) 'start' >> $ENGINEERING_LOG
rsync -aAXv --delete $ENGINEERING_DAILY $ENGINEERING_WEEKLY >> $ENGINEERING_LOG
echo $(date) 'end' >> $ENGINEERING_LOG

